[package]
name = "chatty"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }

[[bin]]
name = "client"

[[bin]]
name = "server"

