name: chaTTY Alpine Linux 3.18

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build with Alpine Linux 3.18
        run: |
          docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp alpine:3.18 sh -c "
            # Install Rust dependencies (Alpine packages and Rust)
            apk update && apk add --no-cache \
              build-base \
              curl \
              git \
              openssl openssl-dev \
              alpine-sdk openssl-dev \
              bash && \
            # Install Rust
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y && \
            source $HOME/.cargo/env && \
            # Build the Rust project
            cargo build --release
          "

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
        
      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

