name: Build chaTTY with Alpine Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [alpine]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust with Alpine
        uses: docker://rust:latest-alpine
        with:
          entrypoint: /bin/sh

      - name: Install build dependencies (Alpine)
        run: |
          apk update
          apk add --no-cache \
            build-base \
            curl \
            git \
            libssl-dev

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Build chaTTY
        run: cargo build --release

